export const GOOGLE_OAUTH_REQUEST = 'GOOGLE_OAUTH_REQUEST';
export const GOOGLE_OAUTH_SUCCESS = 'GOOGLE_OAUTH_SUCCESS';
export const GOOGLE_OAUTH_FAILURE = 'GOOGLE_OAUTH_FAILURE';
export const GOOGLE_OAUTH_CALLBACK = 'GOOGLE_OAUTH_CALLBACK';
