export const themeVars = {
  body: 'var(--body)',
  text: 'var(--text)',
  toggleBorder: 'var(--toggleBorder)',
  chatHoverText: 'var(--chatHoverText)',
  background: 'var(--background)',
  navBg: 'var(--navBg)',
  navBorderColor: 'var(--navBorderColor)',
  inputTextColor: 'var(--inputTextColor)',
  inputBg: 'var(--inputBg)',
  inputBorderColor: 'var(--inputBorderColor)',
  suggestionBg: 'var(--suggestionBg)',
  suggestionHover: 'var(--suggestionHover)',
  cardColor: 'var(--cardColor)',
  searchBarColor: 'var(--searchBarColor)',
  sideBarColor: 'var(--sideBarColor)',
  sideBarHoverColor: 'var(--sideBarHoverColor)',
  togglerColor: 'var(--togglerColor)',
  searchBarFocus: 'var(--searchBarFocus)',
  autoCompleteBackgroundColor: 'var(--autoCompleteBackgroundColor)',
  titleColor: 'var(--titleColor)',
  urlColor: 'var(--urlColor)',
  imageTitleColor: 'var(--imageTitleColor)',
  imageCardColor: 'var(--imageCardColor)',
  textareaBorderColor: 'var(--textareaBorderColor)',
  attachmentColor: 'var(--attachmentColor)',
  red: 'var(--red)',
  white: 'var(--white)',
  black: 'var(--black)',
  grey: 'var(--grey)',
  darkGrey: 'var(--darkGrey)',
  primaryColor: 'var(--primaryColor)',
  secondaryColor: 'var(--secondaryColor)',
  primary: 'var(--primary)',
};

export default themeVars;
